x86-64: Call function via GOT slot with R_X86_64_THUNK_GOTPCRELX
The new R_X86_64_THUNK_GOTPCRELX relocation can be used to call
function via GOT slot.  R_X86_64_THUNK_GOTPCRELX is almost identical
to R_X86_64_REX_GOTPCRELX, except for it is only used to output
indirect branch via GOT slot with call/return thunks.  We convert

	call/jmp *foo@GOTPCREL(%rip)

to

	movq      foo@GOTPCREL_THUNK(%rip), %r11
	call/jmp  __x86_indirect_thunk_r11

when -mindirect-branch=thunk is used.  If foo is defined locally,
linker can convert them to

	call/jmp foo
	nop      0L(%rax)

gcc/

	* configure.ac (HAVE_AS_IX86_THUNK_GOTPCRELX): New.  Defined
	to 1 if assembler and linker support R_X86_64_THUNK_GOTPCRELX.
	* config.in: Regenerated.
	* configure: Likewise.
	* config/i386/i386.c (ix86_output_indirect_branch): Output
	@GOTPCREL_THUNK instead of @GOTPCREL if assembler and linker
	support R_X86_64_THUNK_GOTPCRELX.

gcc/testsuite/

	* gcc.target/i386/indirect-thunk-15.c: New test.
	* gcc.target/i386/indirect-thunk-16.c: Likewise.
	* gcc.target/i386/indirect-thunk-bnd-7.c: Likewise.
	* gcc.target/i386/indirect-thunk-bnd-8.c: Likewise.
	* gcc.target/i386/indirect-thunk-extern-10.c: Likewise.
	* gcc.target/i386/indirect-thunk-extern-11.c: Likewise.
	* lib/target-supports.exp
	(check_effective_target_thunk_gotpcrelx_reloc): New.

diff --git a/gcc/configure b/gcc/configure
--- a/gcc/configure
+++ b/gcc/configure
@@ -26308,6 +26308,53 @@ cat >>confdefs.h <<_ACEOF
 #define HAVE_AS_IX86_TLS_GET_ADDR_GOT `if test x"$gcc_cv_as_ix86_tls_get_addr_via_got" = xyes; then echo 1; else echo 0; fi`
 _ACEOF
 
+
+    conftest_s='
+	.text
+	.global _start
+_start:
+	 movq _start@GOTPCREL_THUNK(%rip), %rax'
+    { $as_echo "$as_me:${as_lineno-$LINENO}: checking assembler for R_X86_64_THUNK_GOTPCRELX reloc" >&5
+$as_echo_n "checking assembler for R_X86_64_THUNK_GOTPCRELX reloc... " >&6; }
+if test "${gcc_cv_as_ix86_thunk_gotpcrelx+set}" = set; then :
+  $as_echo_n "(cached) " >&6
+else
+  gcc_cv_as_ix86_thunk_gotpcrelx=no
+  if test x$gcc_cv_as != x; then
+    $as_echo "$conftest_s" > conftest.s
+    if { ac_try='$gcc_cv_as $gcc_cv_as_flags  -o conftest.o conftest.s >&5'
+  { { eval echo "\"\$as_me\":${as_lineno-$LINENO}: \"$ac_try\""; } >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; }
+    then
+	if test x$gcc_cv_ld != x && test x$gcc_cv_objdump != x \
+	    && test x$gcc_cv_readelf != x \
+	    && $gcc_cv_readelf --relocs --wide conftest.o 2>&1 \
+	       | grep R_X86_64_THUNK_GOTPCRELX > /dev/null 2>&1 \
+	    && $gcc_cv_ld -o conftest conftest.o > /dev/null 2>&1; then
+	   gcc_cv_as_ix86_thunk_gotpcrelx=yes
+	 else
+	   gcc_cv_as_ix86_thunk_gotpcrelx=no
+	 fi
+	 rm -f conftest
+    else
+      echo "configure: failed program was" >&5
+      cat conftest.s >&5
+    fi
+    rm -f conftest.o conftest.s
+  fi
+fi
+{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $gcc_cv_as_ix86_thunk_gotpcrelx" >&5
+$as_echo "$gcc_cv_as_ix86_thunk_gotpcrelx" >&6; }
+
+
+
+cat >>confdefs.h <<_ACEOF
+#define HAVE_AS_IX86_THUNK_GOTPCRELX `if test x"$gcc_cv_as_ix86_thunk_gotpcrelx" = xyes; then echo 1; else echo 0; fi`
+_ACEOF
+
     ;;
 
   ia64*-*-*)
